create table if not exists category (
    id bigint generated by default as identity primary key,
    category_name varchar
);

create table if not exists _limit (
  id bigint generated by default as identity primary key,
  limit_sum double precision,
  limit_datetime timestamp,
  limit_currency_shortname varchar,
  limit_rest double precision,
  account_from bigint,
  category_id bigint references category(id)
);

create table if not exists transaction (
   id bigint generated by default as identity primary key,
   account_from bigint,
   account_to bigint,
   currency_shortname varchar,
   sum double precision,
   expense_category varchar,
   date timestamp,
   limit_exceeded boolean,
   limit_id bigint references _limit(id)
);

create table if not exists meta (
    id bigint generated by default as identity primary key,
    symbol varchar,
    interval varchar,
    currency_base varchar,
    currency_quote varchar,
    type varchar,
    datetime timestamp,
    close double precision
)
