package kz.solva.model.exchange;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Entity
@Table(name = "meta")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Meta {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Long id;
    @Column(name = "symbol")
    String symbol;
    @Column(name = "interval")
    String interval;
    @Column(name = "currency_base")
    String currency_base;
    @Column(name = "currency_quote")
    String currency_quote;
    @Column(name = "type")
    String type;
    @Column(name = "datetime")
    @Temporal(TemporalType.TIMESTAMP)
    Date datetime;
    @Column(name = "close")
    double close;

//    create table meta (
//            id bigint generated by default as identity primary key,
//            symbol varchar,
//            interval varchar,
//            currency_base varchar,
//            currency_quote varchar,
//            type varchar,
//            datetime timestamp,
//            close double precision
//    )


    @Override
    public String toString() {
        return "Meta{" +
                "id=" + id +
                ", symbol='" + symbol + '\'' +
                ", interval='" + interval + '\'' +
                ", currency_base='" + currency_base + '\'' +
                ", currency_quote='" + currency_quote + '\'' +
                ", type='" + type + '\'' +
                ", datetime=" + datetime +
                ", close=" + close +
                '}';
    }
}
